name: ptwcode_country_codes
description: A package to find the calling code and iso code to a country.
version: 1.0.4
repository: https://github.com/alidev0/ptwcode_country_codes

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/